apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-app2
  template:
    metadata:
      labels:
        app: my-backend-app2
    spec:
      containers:
      - name: my-backend-app2
        image: glj/backend:1.0
        ports:
        - containerPort: 8000
