apiVersion: v1
kind: Service
metadata:
  name: my-backend-app2-service
spec:
  selector:
    app: my-backend-app2
  ports:
  - protocol: TCP
    port: 8000        # 服务端口
    targetPort: 8000 # 容器端口
  type: LoadBalancer
