apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-frontend-app
  template:
    metadata:
      labels:
        app: my-frontend-app
    spec:
      containers:
      - name: my-frontend-app
        image: glj/frontend:1.0
        ports:
        - containerPort: 8080
