# Generated by Django 5.0.6 on 2024-06-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question_description', models.CharField(blank=True, max_length=250, null=True)),
                ('is_necessary', models.BooleanField(default=False)),
                ('sequence_id', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('question_type', models.CharField(default='', max_length=30)),
                ('option_num', models.IntegerField(default=0)),
                ('max_option_num', models.IntegerField(default=99999)),
                ('score', models.IntegerField(default=0)),
                ('correct_answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_title', models.CharField(max_length=100)),
                ('survey_description', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('submission_num', models.IntegerField(default=0)),
                ('max_submission', models.ImageField(default=99999, upload_to='')),
                ('is_available', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_collected', models.BooleanField(default=False)),
                ('question_num', models.IntegerField(default=0)),
                ('max_question_num', models.IntegerField(default=99999)),
                ('survey_type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_description', models.CharField(blank=True, max_length=250, null=True)),
                ('sequence_id', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Survey_submit',
            fields=[
                ('survey_submit_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_submit_time', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('survey_score', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question_submit',
            fields=[
                ('question_submit_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=30)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey_submit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey_submit')),
            ],
        ),
    ]
