# Generated by Django 5.0.6 on 2024-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_is_random_survey_share_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_point',
            field=models.IntegerField(default=0),
        ),
    ]
