# Generated by Django 5.0.6 on 2024-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_max_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_submit',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
