# Generated by Django 5.0.6 on 2024-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_question_submit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
