# Generated by Django 5.0.6 on 2024-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_submit',
            name='question_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
