# Generated by Django 5.0.6 on 2024-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_submit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_submit',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
