# Generated by Django 5.0.6 on 2024-06-09 02:54

import image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance', models.ImageField(blank=True, default='', upload_to=image.models.image_path)),
            ],
        ),
    ]
