apiVersion: v1
kind: Service
metadata:
  name: frontend-container-service
spec:
  selector:
    app: frontend-container
  ports:
  - protocol: TCP
    port: 3000     # 服务端口
    targetPort: 8080 # 容器端口
  type: LoadBalancer     
